name: Django Heroku CI/CD

on:
  push:
    branches:
      - main
  
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    # - name: Lint with flake8
    #   run: |
    #     pip install flake8
    #     flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: make migrations
      run: |
        python3 manage.py makemigrations --noinput
        python3 manage.py migrate --noinput
    - name: Django Testing
      run: |
        python3 manage.py test

  deploy-job:

      runs-on: ubuntu-latest
      needs: [build]
      if: ${{ github.event_name == 'push' }}
      steps:
        - uses: actions/checkout@v2
        - name: Deploy to production
          run: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master        



        # - uses: akhileshns/heroku-deploy@v3.12.12
        #   with:
        #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        #     heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
        #     heroku_email: ${{secrets.HEROKU_EMAIL}}
